### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by sylphaxiom** [Wdrussell1/Log4Shell-Automated#1]
While running the script you have here, I am getting an error in the PS console
"error: could not open file; C:\Windows\System32\WindowsPowerShell\Scripts\yara.yar"
I understand that some files might not be able to be traversed, but is this an issue that I should see enough times that it loads up my entire console and keeps populating again and again?

**Comment by Wdrussell1** [comment]
First, be sure you are running powershell as an admin. Also you are attempting to log the files in the system32 directory. It is not advised to log/run from this path. You will likely see access issues if you do. I suggest having a C:\Scripts folder for everything you run.

**Comment by sylphaxiom** [comment]
Thank you very much. That appears to have worked. I'm no longer getting that error anymore.
